
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 4;
  public static final int BOOL = 45;
  public static final int GT = 16;
  public static final int CONST = 52;
  public static final int NOTEQ = 37;
  public static final int PLUSEQ = 40;
  public static final int UNTIL = 66;
  public static final int RBRACK = 12;
  public static final int SIZEOF = 57;
  public static final int COMMA = 14;
  public static final int RPAREN = 10;
  public static final int LBRACK = 11;
  public static final int LT = 17;
  public static final int ANDAND = 38;
  public static final int OROR = 39;
  public static final int DOUBLE = 59;
  public static final int LPAREN = 9;
  public static final int INTEGER_LITERAL = 5;
  public static final int NOT = 18;
  public static final int FLOAT = 53;
  public static final int COMP = 19;
  public static final int RECORD = 55;
  public static final int EQ = 15;
  public static final int MOD = 24;
  public static final int BOOLEAN_LITERAL = 35;
  public static final int PLUS = 71;
  public static final int LONG = 47;
  public static final int LONG_LITERAL = 28;
  public static final int REAL_LITERAL = 27;
  public static final int CHAR = 49;
  public static final int SWITCH = 58;
  public static final int FOR = 44;
  public static final int VOID = 68;
  public static final int EXTERN = 54;
  public static final int DIV = 2;
  public static final int RETURN = 56;
  public static final int MULT = 3;
  public static final int ELSE = 46;
  public static final int BREAK = 51;
  public static final int GTEQ = 33;
  public static final int DOT = 6;
  public static final int INT = 43;
  public static final int STRING_LITERAL = 29;
  public static final int EQEQ = 32;
  public static final int EOF = 0;
  public static final int SEMICOLON = 13;
  public static final int DEFAULT = 60;
  public static final int FUNCTION = 63;
  public static final int MULTEQ = 26;
  public static final int REPEAT = 65;
  public static final int MINUS = 70;
  public static final int LTEQ = 34;
  public static final int IN = 67;
  public static final int OR = 22;
  public static final int error = 1;
  public static final int DIVEQ = 25;
  public static final int CONTINUE = 62;
  public static final int IF = 41;
  public static final int MINUSMINUS = 30;
  public static final int OF = 64;
  public static final int END = 42;
  public static final int COLON = 20;
  public static final int FOREACH = 61;
  public static final int POSPLUS = 74;
  public static final int CHARACTER_LITERAL = 8;
  public static final int BEGIN = 50;
  public static final int CASE = 48;
  public static final int PLUSPLUS = 36;
  public static final int STRING = 7;
  public static final int POSMINUS = 73;
  public static final int AND = 21;
  public static final int UMINUS = 72;
  public static final int AUTO = 69;
  public static final int XOR = 23;
  public static final int MINUSEQ = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIV",
  "MULT",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "DOT",
  "STRING",
  "CHARACTER_LITERAL",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "SEMICOLON",
  "COMMA",
  "EQ",
  "GT",
  "LT",
  "NOT",
  "COMP",
  "COLON",
  "AND",
  "OR",
  "XOR",
  "MOD",
  "DIVEQ",
  "MULTEQ",
  "REAL_LITERAL",
  "LONG_LITERAL",
  "STRING_LITERAL",
  "MINUSMINUS",
  "MINUSEQ",
  "EQEQ",
  "GTEQ",
  "LTEQ",
  "BOOLEAN_LITERAL",
  "PLUSPLUS",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUSEQ",
  "IF",
  "END",
  "INT",
  "FOR",
  "BOOL",
  "ELSE",
  "LONG",
  "CASE",
  "CHAR",
  "BEGIN",
  "BREAK",
  "CONST",
  "FLOAT",
  "EXTERN",
  "RECORD",
  "RETURN",
  "SIZEOF",
  "SWITCH",
  "DOUBLE",
  "DEFAULT",
  "FOREACH",
  "CONTINUE",
  "FUNCTION",
  "OF",
  "REPEAT",
  "UNTIL",
  "IN",
  "VOID",
  "AUTO",
  "MINUS",
  "PLUS",
  "UMINUS",
  "POSMINUS",
  "POSPLUS"
  };
}

